import { NextRequest, NextResponse } from 'next/server';
import { CG_AG_CONTROLS } from '@council/scanner';

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/v1/standard          → CG-AG spec (JSON)
// GET /api/v1/standard?format=md → CG-AG spec (Markdown, publishable)
// The open standard for AI Agent Governance — 12 controls.
// ─────────────────────────────────────────────────────────────────────────────

const TRACEABILITY: Record<string, { aiAct?: string; dora?: string; iso42001?: string; nist?: string }> = {
  'CG-AG-001': { aiAct: 'Art. 16 (provider obligations)', iso42001: 'A.6.2 (AI system inventory)', nist: 'GOVERN 1.1' },
  'CG-AG-002': { aiAct: 'Art. 26 (deployer obligations)', iso42001: 'A.3.2 (roles & responsibilities)', nist: 'GOVERN 2.1' },
  'CG-AG-003': { aiAct: 'Art. 11 (technical documentation)', iso42001: 'A.7.2 (data & model documentation)', nist: 'MAP 2.3' },
  'CG-AG-004': { aiAct: 'Art. 9 (risk management)', dora: 'Art. 9 (ICT protection)', iso42001: 'A.5.3 (access control)' },
  'CG-AG-005': { aiAct: 'Art. 15 (accuracy & robustness)', nist: 'MEASURE 2.7 (prompt injection)' },
  'CG-AG-006': { dora: 'Art. 28 (third-party ICT)', iso42001: 'A.10.3 (supplier AI)', nist: 'GOVERN 6.1' },
  'CG-AG-007': { aiAct: 'Art. 14 (human oversight)', iso42001: 'A.8.4 (human oversight)', nist: 'GOVERN 3.2' },
  'CG-AG-008': { aiAct: 'Art. 12 (record-keeping/logs)', dora: 'Art. 12 (logging)', iso42001: 'A.6.7 (event logs)' },
  'CG-AG-009': { aiAct: 'Art. 10 (data governance)', iso42001: 'A.7.3 (data quality)', nist: 'MAP 2.2' },
  'CG-AG-010': { aiAct: 'Art. 6 + Annex III (classification)', iso42001: 'A.5.2 (risk assessment)', nist: 'MAP 1.5' },
  'CG-AG-011': { aiAct: 'Art. 9 (interaction risk)', dora: 'Art. 30 (chain outsourcing)', nist: 'MEASURE 2.9' },
  'CG-AG-012': { aiAct: 'Art. 14 (autonomous oversight)', iso42001: 'A.8.4', nist: 'GOVERN 3.2 / MANAGE 2.4' },
};

function buildSpec() {
  const controls = Object.values(CG_AG_CONTROLS).map(c => ({
    id: c.id,
    name: c.name,
    domain: c.domain,
    description: c.description,
    traceability: TRACEABILITY[c.id] ?? {},
  }));
  return {
    standard: 'CG-AG — CodeGuard Agent Governance Framework',
    version: '1.0.0',
    license: 'CC BY 4.0',
    purpose: 'The open standard for AI agent governance. Every AI agent in production should satisfy these 12 controls.',
    mappedFrameworks: ['EU AI Act 2024/1689', 'DORA (EU) 2022/2554', 'ISO/IEC 42001:2023', 'NIST AI RMF 1.0'],
    controls,
  };
}

function toMarkdown(spec: ReturnType<typeof buildSpec>): string {
  const lines: string[] = [
    `# ${spec.standard}`,
    ``,
    `**Version:** ${spec.version} | **License:** ${spec.license}`,
    ``,
    `> ${spec.purpose}`,
    ``,
    `Mapped to: ${spec.mappedFrameworks.join(' · ')}`,
    ``,
    `## The 12 Controls`,
    ``,
    `| ID | Control | Domain | Requirement |`,
    `|----|---------|--------|-------------|`,
  ];
  for (const c of spec.controls) {
    lines.push(`| **${c.id}** | ${c.name} | ${c.domain} | ${c.description} |`);
  }
  lines.push('', '## Regulatory Traceability', '');
  lines.push(`| Control | EU AI Act | DORA | ISO/IEC 42001 | NIST AI RMF |`);
  lines.push(`|---------|-----------|------|----------------|-------------|`);
  for (const c of spec.controls) {
    const t = c.traceability;
    lines.push(`| ${c.id} | ${t.aiAct ?? '—'} | ${t.dora ?? '—'} | ${t.iso42001 ?? '—'} | ${t.nist ?? '—'} |`);
  }
  lines.push('', '---', '', '*Generated by CodeGuard AI Governance OS. The future problem is not creating AI agents — it is governing thousands of them.*');
  return lines.join('\n');
}

export async function GET(req: NextRequest) {
  const format = new URL(req.url).searchParams.get('format');
  const spec = buildSpec();
  if (format === 'md' || format === 'markdown') {
    return new NextResponse(toMarkdown(spec), {
      status: 200,
      headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
    });
  }
  return NextResponse.json({ ok: true, data: spec });
}
