// Backward-compatible relationship types
export type { RelKind, Relationship } from '../types';

export interface RelationshipDef { label: string; color?: string; description?: string; }

export const RELATIONSHIP_DEFS: Record<string, RelationshipDef> = {
  MAKES_DECISION: { label: 'Makes Decision', color: '#6366F1' },
  BASED_ON: { label: 'Based On', color: '#8B5CF6' },
  USES_TOOL: { label: 'Uses Tool', color: '#5B50F0' },
  USES_MODEL: { label: 'Uses Model', color: '#06B6D4' },
  USES_PROMPT: { label: 'Uses Prompt', color: '#F0AB00' },
  USES_MEMORY: { label: 'Uses Memory', color: '#8B5CF6' },
  PROCESSES_DATA: { label: 'Processes Data', color: '#F59E0B' },
  DEPLOYS_IN: { label: 'Deploys In', color: '#14B8A6' },
  DEPENDS_ON: { label: 'Depends On', color: '#6B7A95' },
  INTEGRATES_WITH: { label: 'Integrates With', color: '#6366F1' },
  EVIDENCED_BY: { label: 'Evidenced By', color: '#22C55E' },
  IMPACTS_RISK: { label: 'Impacts Risk', color: '#EF4444' },
  TRIGGERS_INCIDENT: { label: 'Triggers Incident', color: '#F97316' },
  REGULATES: { label: 'Regulates', color: '#94A3B8' },
  GOVERNS: { label: 'Governs', color: '#A855F7' },
  OWNS: { label: 'Owns', color: '#EC4899' },
  REQUIRES_CERT: { label: 'Requires Cert', color: '#A855F7' },
  AUDITS: { label: 'Audits', color: '#6366F1' },
  REVIEWS: { label: 'Reviews', color: '#F0AB00' },
  MONITORS: { label: 'Monitors', color: '#0ECFB8' },
  APPEALS_CONTROL: { label: 'Appeals Control', color: '#F87171' },
  CONTAINS: { label: 'Contains', color: '#6B7A95' },
  COSTS: { label: 'Costs', color: '#14B8A6' },
  ACCESSES_SYSTEM: { label: 'Accesses System', color: '#F87171' },
  OWNED_BY: { label: 'Owned By', color: '#EC4899' },
  GENERATED_BY_PROMPT: { label: 'Generated By Prompt', color: '#F0AB00' },
};
